---
title: "Vignette: Robust Survey Statistics Estimation"
author: "Beat Hulliger and Tobias Schoch (package vers. 0.2)"
output:
    html_document:
        highlight: tango
vignette: >
  %\VignetteIndexEntry{Robust Survey Statistics Estimation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "",
    prompt = TRUE
)
```

```{css, echo = FALSE}
.my-callout {
    padding: 1.25rem;
    margin-top: 1.25rem;
    margin-bottom: 1.25rem;
    border: 1px solid #eee;
    border-left-width: 0.75rem;
    border-left-color: #df536b;
    border-radius: .25rem
}
```

## Introduction

The package `robsurvey` implements [Béguin and Hulliger](#biblio) (2002)


```{r}
library(robsurvey, quietly = TRUE)
data(workplace)
weighted_mean_huber(workplace$payroll, workplace$weight)
```

---

## References {#biblio}

Béguin, C. and B. Hulliger (2002). *Robust Multivariate Outlier Detection and Imputation with Incomplete Survey Data*, Deliverable D4/5.2.1/2 Part C: EUREDIT project, https://www.cs.york.ac.uk/euredit/euredit-main.html, research project funded by the European Commission, IST-1999-10226.
